-- Add avatar headshot URL column to store generated avatar profile photos
-- Headshots are generated by the in-app custom avatar editor.

ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS avatar_headshot_url TEXT;

-- Add comment for documentation
COMMENT ON COLUMN profiles.avatar_headshot_url IS 'URL to generated avatar headshot image, created when user saves avatar customization';
